# 2.1 理解Python中的数据类型

要实现高效的数据驱动科学和计算，需要理解数据是如何被存储和操作的。  
  
在静态类型的语言（如C或Java）中，往往每一个变量的类型都需要明确的声明。而在动态类型的语言（如Python）中，可以跳过这个特殊的规定，因为类型是动态判断的。这意味着可以将任何类型的数据指定给任何变量：

In [ ]:
x = 4 #int
x = 'four' #string

这种灵活特性还指出了一个事实，Python变量不仅是它们的值，还包括了关于值的类型的一些额外的信息。

In [1]:
import numpy as np #用np别名导入Numpy

## 从Python列表创建数组

首先，可以用`np.array`从Python列表中创建数组：

In [2]:
np.array([1,4,2,5,3]) #整形数组

array([1, 4, 2, 5, 3])

NumPy要求数组必须包含同一类型的数据。如果数据类型不匹配，NumPy将会向上转换（如果可行）。

In [3]:
np.array([3.14,4,2,3]) #整型被转换为浮点型

array([3.14, 4.  , 2.  , 3.  ])

如果希望明确设置数组的数据类型，可以使用`dtype`关键字：

In [4]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

最后，不同于Python列表，NumPy数组可以被指定为多维的。

In [5]:
np.array([range(i,i+3) for i in [2,4,6]]) #嵌套列表构成的多维数组

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

内层的列表被当作为二维数组的行。

## 从头创建数组

面对大型数组的时候，用NumPy内置的方法从头创建数组是一种更高效的方法。  
  
以下是几个示例：

In [6]:
np.zeros(10,dtype=int) #创建一个长度为10的数组，数组的值都是0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
np.ones((3,5),dtype=float) #创建一个3x5的浮点型数组，数组的值都是1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((3,5),3.14) #创建一个3x5的浮点型数组，数组的值都是3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
#创建一个线性序列数组
#从0开始，到20结束，步长为2
#（它和内置的range()函数类似）
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
#创建一个5个元素的数组，着5个数均匀地被分配到0-1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
#创建一个3x3的、在0-1均匀分布的随机数组成的数组
np.random.random((3,3))

array([[0.22520583, 0.58987756, 0.65546684],
       [0.64602092, 0.29206662, 0.27499691],
       [0.35867305, 0.7197953 , 0.91942788]])

In [12]:
#创建一个3x3的、均值为0、标准差为1的、正态分布的随机数数组
np.random.normal(0,1,(3,3))

array([[ 0.33868687,  1.39903201,  1.75153908],
       [ 0.53825408,  0.54126826, -0.64770791],
       [ 1.70502685,  1.5180098 ,  1.94053406]])

In [13]:
#创建一个3x3的、[0,10)区间的随机整数型数组
np.random.randint(0,10,(3,3))

array([[2, 3, 2],
       [6, 3, 0],
       [5, 3, 0]])

In [14]:
#创建一个3x3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#创建一个由3个整型数组成的未初始化的数组
#数组的值是内存空间中的任意值
np.empty(3)

array([1., 1., 1.])

## NumPy标准数据类型

NumPy数组包含同一类型的值，因此详细了解这些数据类型及其限制是非常重要的。  
  
请注意，当构建一个数组时，可以用一个字符串参数来指定数据类型：

In [16]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

或者用相关的NumPy对象来指定：

In [17]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

**NumPy标准数据类型**

| 数据类型 | 描述 |
| :----- | :----- |
| bool_ | 布尔值（真、True或假、False）,用一个字节存储 |
| int_ | 默认整型（类似于C语言中的long,通常情况下是int64或int32）|
| intc | t同C语言中的int相同（通常是int32或int64）|
| intp | 作为索引的整型（和C语言的ssize_t相同，通常情况下是int32或int64)|
| int8 | 字节（byte，范围从-128到127）|
| int16 | 整型（范围从-32768到32767）|
| int32 | 整型（范围从-2147483648到2147483647）|
| int64 | 整型（范围从-9223372036854775808到9223372036854775807）|
| uint8 | 无符号整型（范围从0到255）|
| uint16 | 无符号整型（范围从0到65535）|
| uint32 | 无符号整型（范围从0到4294967295）|
| uint64 | 无符号整型（范围从0到18446744073709551615）|
| float_ | float64的简化形式 |
| float16 | 半精度浮点型：符号比特位，5比特指数(exponent),10比特位尾数(mantissa) |
| float32 | 单精度浮点型：符号比特位，8比特指数,23比特位尾数 |
| float64 | 双精度浮点型：符号比特位，11比特指数,52比特位尾数 |
| complex_ | complex128的简化形式 |
| complex64 | 复数，由两个32位浮点数表示 |
| complex128 | 复数，由两个64位浮点数表示 |

NumPy支持符合数据类型，这一点将会在2.9节中介绍。